// Code generated by go-swagger; DO NOT EDIT.

package posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dstuart/medium_client/models"
)

// PostPublicationsPublicationIDPostsReader is a Reader for the PostPublicationsPublicationIDPosts structure.
type PostPublicationsPublicationIDPostsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostPublicationsPublicationIDPostsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostPublicationsPublicationIDPostsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostPublicationsPublicationIDPostsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostPublicationsPublicationIDPostsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostPublicationsPublicationIDPostsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /publications/{publicationId}/posts] PostPublicationsPublicationIDPosts", response, response.Code())
	}
}

// NewPostPublicationsPublicationIDPostsOK creates a PostPublicationsPublicationIDPostsOK with default headers values
func NewPostPublicationsPublicationIDPostsOK() *PostPublicationsPublicationIDPostsOK {
	return &PostPublicationsPublicationIDPostsOK{}
}

/*
PostPublicationsPublicationIDPostsOK describes a response with status code 200, with default header values.

OK
*/
type PostPublicationsPublicationIDPostsOK struct {
	Payload *models.PostDetails
}

// IsSuccess returns true when this post publications publication Id posts o k response has a 2xx status code
func (o *PostPublicationsPublicationIDPostsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post publications publication Id posts o k response has a 3xx status code
func (o *PostPublicationsPublicationIDPostsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post publications publication Id posts o k response has a 4xx status code
func (o *PostPublicationsPublicationIDPostsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post publications publication Id posts o k response has a 5xx status code
func (o *PostPublicationsPublicationIDPostsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post publications publication Id posts o k response a status code equal to that given
func (o *PostPublicationsPublicationIDPostsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post publications publication Id posts o k response
func (o *PostPublicationsPublicationIDPostsOK) Code() int {
	return 200
}

func (o *PostPublicationsPublicationIDPostsOK) Error() string {
	return fmt.Sprintf("[POST /publications/{publicationId}/posts][%d] postPublicationsPublicationIdPostsOK  %+v", 200, o.Payload)
}

func (o *PostPublicationsPublicationIDPostsOK) String() string {
	return fmt.Sprintf("[POST /publications/{publicationId}/posts][%d] postPublicationsPublicationIdPostsOK  %+v", 200, o.Payload)
}

func (o *PostPublicationsPublicationIDPostsOK) GetPayload() *models.PostDetails {
	return o.Payload
}

func (o *PostPublicationsPublicationIDPostsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostPublicationsPublicationIDPostsBadRequest creates a PostPublicationsPublicationIDPostsBadRequest with default headers values
func NewPostPublicationsPublicationIDPostsBadRequest() *PostPublicationsPublicationIDPostsBadRequest {
	return &PostPublicationsPublicationIDPostsBadRequest{}
}

/*
PostPublicationsPublicationIDPostsBadRequest describes a response with status code 400, with default header values.

Required fields were invalid, not specified.
*/
type PostPublicationsPublicationIDPostsBadRequest struct {
}

// IsSuccess returns true when this post publications publication Id posts bad request response has a 2xx status code
func (o *PostPublicationsPublicationIDPostsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post publications publication Id posts bad request response has a 3xx status code
func (o *PostPublicationsPublicationIDPostsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post publications publication Id posts bad request response has a 4xx status code
func (o *PostPublicationsPublicationIDPostsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post publications publication Id posts bad request response has a 5xx status code
func (o *PostPublicationsPublicationIDPostsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post publications publication Id posts bad request response a status code equal to that given
func (o *PostPublicationsPublicationIDPostsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post publications publication Id posts bad request response
func (o *PostPublicationsPublicationIDPostsBadRequest) Code() int {
	return 400
}

func (o *PostPublicationsPublicationIDPostsBadRequest) Error() string {
	return fmt.Sprintf("[POST /publications/{publicationId}/posts][%d] postPublicationsPublicationIdPostsBadRequest ", 400)
}

func (o *PostPublicationsPublicationIDPostsBadRequest) String() string {
	return fmt.Sprintf("[POST /publications/{publicationId}/posts][%d] postPublicationsPublicationIdPostsBadRequest ", 400)
}

func (o *PostPublicationsPublicationIDPostsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostPublicationsPublicationIDPostsUnauthorized creates a PostPublicationsPublicationIDPostsUnauthorized with default headers values
func NewPostPublicationsPublicationIDPostsUnauthorized() *PostPublicationsPublicationIDPostsUnauthorized {
	return &PostPublicationsPublicationIDPostsUnauthorized{}
}

/*
PostPublicationsPublicationIDPostsUnauthorized describes a response with status code 401, with default header values.

The `accessToken` is invalid or has been revoked.
*/
type PostPublicationsPublicationIDPostsUnauthorized struct {
}

// IsSuccess returns true when this post publications publication Id posts unauthorized response has a 2xx status code
func (o *PostPublicationsPublicationIDPostsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post publications publication Id posts unauthorized response has a 3xx status code
func (o *PostPublicationsPublicationIDPostsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post publications publication Id posts unauthorized response has a 4xx status code
func (o *PostPublicationsPublicationIDPostsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post publications publication Id posts unauthorized response has a 5xx status code
func (o *PostPublicationsPublicationIDPostsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post publications publication Id posts unauthorized response a status code equal to that given
func (o *PostPublicationsPublicationIDPostsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post publications publication Id posts unauthorized response
func (o *PostPublicationsPublicationIDPostsUnauthorized) Code() int {
	return 401
}

func (o *PostPublicationsPublicationIDPostsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /publications/{publicationId}/posts][%d] postPublicationsPublicationIdPostsUnauthorized ", 401)
}

func (o *PostPublicationsPublicationIDPostsUnauthorized) String() string {
	return fmt.Sprintf("[POST /publications/{publicationId}/posts][%d] postPublicationsPublicationIdPostsUnauthorized ", 401)
}

func (o *PostPublicationsPublicationIDPostsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostPublicationsPublicationIDPostsForbidden creates a PostPublicationsPublicationIDPostsForbidden with default headers values
func NewPostPublicationsPublicationIDPostsForbidden() *PostPublicationsPublicationIDPostsForbidden {
	return &PostPublicationsPublicationIDPostsForbidden{}
}

/*
PostPublicationsPublicationIDPostsForbidden describes a response with status code 403, with default header values.

The `publicationId` in request path doesn’t point to a publication that the user can publish into.
*/
type PostPublicationsPublicationIDPostsForbidden struct {
}

// IsSuccess returns true when this post publications publication Id posts forbidden response has a 2xx status code
func (o *PostPublicationsPublicationIDPostsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post publications publication Id posts forbidden response has a 3xx status code
func (o *PostPublicationsPublicationIDPostsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post publications publication Id posts forbidden response has a 4xx status code
func (o *PostPublicationsPublicationIDPostsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post publications publication Id posts forbidden response has a 5xx status code
func (o *PostPublicationsPublicationIDPostsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post publications publication Id posts forbidden response a status code equal to that given
func (o *PostPublicationsPublicationIDPostsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post publications publication Id posts forbidden response
func (o *PostPublicationsPublicationIDPostsForbidden) Code() int {
	return 403
}

func (o *PostPublicationsPublicationIDPostsForbidden) Error() string {
	return fmt.Sprintf("[POST /publications/{publicationId}/posts][%d] postPublicationsPublicationIdPostsForbidden ", 403)
}

func (o *PostPublicationsPublicationIDPostsForbidden) String() string {
	return fmt.Sprintf("[POST /publications/{publicationId}/posts][%d] postPublicationsPublicationIdPostsForbidden ", 403)
}

func (o *PostPublicationsPublicationIDPostsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
