// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dstuart/models"
)

// NewPostUsersAuthorIDPostsParams creates a new PostUsersAuthorIDPostsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostUsersAuthorIDPostsParams() *PostUsersAuthorIDPostsParams {
	return &PostUsersAuthorIDPostsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostUsersAuthorIDPostsParamsWithTimeout creates a new PostUsersAuthorIDPostsParams object
// with the ability to set a timeout on a request.
func NewPostUsersAuthorIDPostsParamsWithTimeout(timeout time.Duration) *PostUsersAuthorIDPostsParams {
	return &PostUsersAuthorIDPostsParams{
		timeout: timeout,
	}
}

// NewPostUsersAuthorIDPostsParamsWithContext creates a new PostUsersAuthorIDPostsParams object
// with the ability to set a context for a request.
func NewPostUsersAuthorIDPostsParamsWithContext(ctx context.Context) *PostUsersAuthorIDPostsParams {
	return &PostUsersAuthorIDPostsParams{
		Context: ctx,
	}
}

// NewPostUsersAuthorIDPostsParamsWithHTTPClient creates a new PostUsersAuthorIDPostsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostUsersAuthorIDPostsParamsWithHTTPClient(client *http.Client) *PostUsersAuthorIDPostsParams {
	return &PostUsersAuthorIDPostsParams{
		HTTPClient: client,
	}
}

/*
PostUsersAuthorIDPostsParams contains all the parameters to send to the API endpoint

	for the post users author ID posts operation.

	Typically these are written to a http.Request.
*/
type PostUsersAuthorIDPostsParams struct {

	/* AuthorID.

	   authorId is the user id of the authenticated user.
	*/
	AuthorID string

	/* Body.

	   Creates a post for user.
	*/
	Body *models.Post

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post users author ID posts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostUsersAuthorIDPostsParams) WithDefaults() *PostUsersAuthorIDPostsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post users author ID posts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostUsersAuthorIDPostsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post users author ID posts params
func (o *PostUsersAuthorIDPostsParams) WithTimeout(timeout time.Duration) *PostUsersAuthorIDPostsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post users author ID posts params
func (o *PostUsersAuthorIDPostsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post users author ID posts params
func (o *PostUsersAuthorIDPostsParams) WithContext(ctx context.Context) *PostUsersAuthorIDPostsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post users author ID posts params
func (o *PostUsersAuthorIDPostsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post users author ID posts params
func (o *PostUsersAuthorIDPostsParams) WithHTTPClient(client *http.Client) *PostUsersAuthorIDPostsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post users author ID posts params
func (o *PostUsersAuthorIDPostsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorID adds the authorID to the post users author ID posts params
func (o *PostUsersAuthorIDPostsParams) WithAuthorID(authorID string) *PostUsersAuthorIDPostsParams {
	o.SetAuthorID(authorID)
	return o
}

// SetAuthorID adds the authorId to the post users author ID posts params
func (o *PostUsersAuthorIDPostsParams) SetAuthorID(authorID string) {
	o.AuthorID = authorID
}

// WithBody adds the body to the post users author ID posts params
func (o *PostUsersAuthorIDPostsParams) WithBody(body *models.Post) *PostUsersAuthorIDPostsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post users author ID posts params
func (o *PostUsersAuthorIDPostsParams) SetBody(body *models.Post) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostUsersAuthorIDPostsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param authorId
	if err := r.SetPathParam("authorId", o.AuthorID); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
