// Code generated by go-swagger; DO NOT EDIT.

package publications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPublicationsPublicationIDContributorsParams creates a new GetPublicationsPublicationIDContributorsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPublicationsPublicationIDContributorsParams() *GetPublicationsPublicationIDContributorsParams {
	return &GetPublicationsPublicationIDContributorsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPublicationsPublicationIDContributorsParamsWithTimeout creates a new GetPublicationsPublicationIDContributorsParams object
// with the ability to set a timeout on a request.
func NewGetPublicationsPublicationIDContributorsParamsWithTimeout(timeout time.Duration) *GetPublicationsPublicationIDContributorsParams {
	return &GetPublicationsPublicationIDContributorsParams{
		timeout: timeout,
	}
}

// NewGetPublicationsPublicationIDContributorsParamsWithContext creates a new GetPublicationsPublicationIDContributorsParams object
// with the ability to set a context for a request.
func NewGetPublicationsPublicationIDContributorsParamsWithContext(ctx context.Context) *GetPublicationsPublicationIDContributorsParams {
	return &GetPublicationsPublicationIDContributorsParams{
		Context: ctx,
	}
}

// NewGetPublicationsPublicationIDContributorsParamsWithHTTPClient creates a new GetPublicationsPublicationIDContributorsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPublicationsPublicationIDContributorsParamsWithHTTPClient(client *http.Client) *GetPublicationsPublicationIDContributorsParams {
	return &GetPublicationsPublicationIDContributorsParams{
		HTTPClient: client,
	}
}

/*
GetPublicationsPublicationIDContributorsParams contains all the parameters to send to the API endpoint

	for the get publications publication ID contributors operation.

	Typically these are written to a http.Request.
*/
type GetPublicationsPublicationIDContributorsParams struct {

	/* PublicationID.

	   A unique identifier for the publication.
	*/
	PublicationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get publications publication ID contributors params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPublicationsPublicationIDContributorsParams) WithDefaults() *GetPublicationsPublicationIDContributorsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get publications publication ID contributors params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPublicationsPublicationIDContributorsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get publications publication ID contributors params
func (o *GetPublicationsPublicationIDContributorsParams) WithTimeout(timeout time.Duration) *GetPublicationsPublicationIDContributorsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get publications publication ID contributors params
func (o *GetPublicationsPublicationIDContributorsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get publications publication ID contributors params
func (o *GetPublicationsPublicationIDContributorsParams) WithContext(ctx context.Context) *GetPublicationsPublicationIDContributorsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get publications publication ID contributors params
func (o *GetPublicationsPublicationIDContributorsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get publications publication ID contributors params
func (o *GetPublicationsPublicationIDContributorsParams) WithHTTPClient(client *http.Client) *GetPublicationsPublicationIDContributorsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get publications publication ID contributors params
func (o *GetPublicationsPublicationIDContributorsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPublicationID adds the publicationID to the get publications publication ID contributors params
func (o *GetPublicationsPublicationIDContributorsParams) WithPublicationID(publicationID string) *GetPublicationsPublicationIDContributorsParams {
	o.SetPublicationID(publicationID)
	return o
}

// SetPublicationID adds the publicationId to the get publications publication ID contributors params
func (o *GetPublicationsPublicationIDContributorsParams) SetPublicationID(publicationID string) {
	o.PublicationID = publicationID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPublicationsPublicationIDContributorsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param publicationId
	if err := r.SetPathParam("publicationId", o.PublicationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
