// Code generated by go-swagger; DO NOT EDIT.

package publications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUsersUserIDPublicationsParams creates a new GetUsersUserIDPublicationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUsersUserIDPublicationsParams() *GetUsersUserIDPublicationsParams {
	return &GetUsersUserIDPublicationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsersUserIDPublicationsParamsWithTimeout creates a new GetUsersUserIDPublicationsParams object
// with the ability to set a timeout on a request.
func NewGetUsersUserIDPublicationsParamsWithTimeout(timeout time.Duration) *GetUsersUserIDPublicationsParams {
	return &GetUsersUserIDPublicationsParams{
		timeout: timeout,
	}
}

// NewGetUsersUserIDPublicationsParamsWithContext creates a new GetUsersUserIDPublicationsParams object
// with the ability to set a context for a request.
func NewGetUsersUserIDPublicationsParamsWithContext(ctx context.Context) *GetUsersUserIDPublicationsParams {
	return &GetUsersUserIDPublicationsParams{
		Context: ctx,
	}
}

// NewGetUsersUserIDPublicationsParamsWithHTTPClient creates a new GetUsersUserIDPublicationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUsersUserIDPublicationsParamsWithHTTPClient(client *http.Client) *GetUsersUserIDPublicationsParams {
	return &GetUsersUserIDPublicationsParams{
		HTTPClient: client,
	}
}

/*
GetUsersUserIDPublicationsParams contains all the parameters to send to the API endpoint

	for the get users user ID publications operation.

	Typically these are written to a http.Request.
*/
type GetUsersUserIDPublicationsParams struct {

	/* UserID.

	   A unique identifier for the user.
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get users user ID publications params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUsersUserIDPublicationsParams) WithDefaults() *GetUsersUserIDPublicationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get users user ID publications params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUsersUserIDPublicationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get users user ID publications params
func (o *GetUsersUserIDPublicationsParams) WithTimeout(timeout time.Duration) *GetUsersUserIDPublicationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get users user ID publications params
func (o *GetUsersUserIDPublicationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get users user ID publications params
func (o *GetUsersUserIDPublicationsParams) WithContext(ctx context.Context) *GetUsersUserIDPublicationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get users user ID publications params
func (o *GetUsersUserIDPublicationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get users user ID publications params
func (o *GetUsersUserIDPublicationsParams) WithHTTPClient(client *http.Client) *GetUsersUserIDPublicationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get users user ID publications params
func (o *GetUsersUserIDPublicationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the get users user ID publications params
func (o *GetUsersUserIDPublicationsParams) WithUserID(userID string) *GetUsersUserIDPublicationsParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get users user ID publications params
func (o *GetUsersUserIDPublicationsParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsersUserIDPublicationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
