// Code generated by go-swagger; DO NOT EDIT.

package publications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dstuart/models"
)

// GetPublicationsPublicationIDContributorsReader is a Reader for the GetPublicationsPublicationIDContributors structure.
type GetPublicationsPublicationIDContributorsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPublicationsPublicationIDContributorsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPublicationsPublicationIDContributorsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetPublicationsPublicationIDContributorsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /publications/{publicationId}/contributors] GetPublicationsPublicationIDContributors", response, response.Code())
	}
}

// NewGetPublicationsPublicationIDContributorsOK creates a GetPublicationsPublicationIDContributorsOK with default headers values
func NewGetPublicationsPublicationIDContributorsOK() *GetPublicationsPublicationIDContributorsOK {
	return &GetPublicationsPublicationIDContributorsOK{}
}

/*
GetPublicationsPublicationIDContributorsOK describes a response with status code 200, with default header values.

OK
*/
type GetPublicationsPublicationIDContributorsOK struct {
	Payload *models.ContibutorResponse
}

// IsSuccess returns true when this get publications publication Id contributors o k response has a 2xx status code
func (o *GetPublicationsPublicationIDContributorsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get publications publication Id contributors o k response has a 3xx status code
func (o *GetPublicationsPublicationIDContributorsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get publications publication Id contributors o k response has a 4xx status code
func (o *GetPublicationsPublicationIDContributorsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get publications publication Id contributors o k response has a 5xx status code
func (o *GetPublicationsPublicationIDContributorsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get publications publication Id contributors o k response a status code equal to that given
func (o *GetPublicationsPublicationIDContributorsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get publications publication Id contributors o k response
func (o *GetPublicationsPublicationIDContributorsOK) Code() int {
	return 200
}

func (o *GetPublicationsPublicationIDContributorsOK) Error() string {
	return fmt.Sprintf("[GET /publications/{publicationId}/contributors][%d] getPublicationsPublicationIdContributorsOK  %+v", 200, o.Payload)
}

func (o *GetPublicationsPublicationIDContributorsOK) String() string {
	return fmt.Sprintf("[GET /publications/{publicationId}/contributors][%d] getPublicationsPublicationIdContributorsOK  %+v", 200, o.Payload)
}

func (o *GetPublicationsPublicationIDContributorsOK) GetPayload() *models.ContibutorResponse {
	return o.Payload
}

func (o *GetPublicationsPublicationIDContributorsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContibutorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPublicationsPublicationIDContributorsUnauthorized creates a GetPublicationsPublicationIDContributorsUnauthorized with default headers values
func NewGetPublicationsPublicationIDContributorsUnauthorized() *GetPublicationsPublicationIDContributorsUnauthorized {
	return &GetPublicationsPublicationIDContributorsUnauthorized{}
}

/*
GetPublicationsPublicationIDContributorsUnauthorized describes a response with status code 401, with default header values.

The `accessToken` is invalid or has been revoked.
*/
type GetPublicationsPublicationIDContributorsUnauthorized struct {
}

// IsSuccess returns true when this get publications publication Id contributors unauthorized response has a 2xx status code
func (o *GetPublicationsPublicationIDContributorsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get publications publication Id contributors unauthorized response has a 3xx status code
func (o *GetPublicationsPublicationIDContributorsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get publications publication Id contributors unauthorized response has a 4xx status code
func (o *GetPublicationsPublicationIDContributorsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get publications publication Id contributors unauthorized response has a 5xx status code
func (o *GetPublicationsPublicationIDContributorsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get publications publication Id contributors unauthorized response a status code equal to that given
func (o *GetPublicationsPublicationIDContributorsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get publications publication Id contributors unauthorized response
func (o *GetPublicationsPublicationIDContributorsUnauthorized) Code() int {
	return 401
}

func (o *GetPublicationsPublicationIDContributorsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /publications/{publicationId}/contributors][%d] getPublicationsPublicationIdContributorsUnauthorized ", 401)
}

func (o *GetPublicationsPublicationIDContributorsUnauthorized) String() string {
	return fmt.Sprintf("[GET /publications/{publicationId}/contributors][%d] getPublicationsPublicationIdContributorsUnauthorized ", 401)
}

func (o *GetPublicationsPublicationIDContributorsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
