// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Contibutor Contributor
//
// # Contibutor
//
// swagger:model Contibutor
type Contibutor struct {

	// An ID for the publication. This can be lifted from response of publications above
	PublicationID string `json:"publicationId,omitempty"`

	// Role of the user identified by userId in the publication identified by `publicationId`. *editor* or *writer*
	Role string `json:"role,omitempty"`

	// A user ID of the contributor.
	UserID string `json:"userId,omitempty"`
}

// Validate validates this contibutor
func (m *Contibutor) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this contibutor based on context it is used
func (m *Contibutor) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Contibutor) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Contibutor) UnmarshalBinary(b []byte) error {
	var res Contibutor
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
