// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Publication Publication Info
//
// Publications provide a way for authors to work collaboratively within a common narrative framework, brand or point of view.
// Example: {"description":"What is this thing and how does it work?","id":"b969ac62a46b","imageUrl":"https://cdn-images-1.medium.com/fit/c/200/200/0*ae1jbP_od0W6EulE.jpeg","name":"About Medium","url":"https://medium.com/about"}
//
// swagger:model Publication
type Publication struct {

	// Short description of the publication
	Description string `json:"description,omitempty"`

	// A unique identifier for the publication.
	ID string `json:"id,omitempty"`

	// The URL to the publication’s image/logo
	ImageURL string `json:"imageUrl,omitempty"`

	// The publication’s name on Medium.
	Name string `json:"name,omitempty"`

	// The URL to the publication’s homepage
	URL string `json:"url,omitempty"`
}

// Validate validates this publication
func (m *Publication) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this publication based on context it is used
func (m *Publication) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Publication) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Publication) UnmarshalBinary(b []byte) error {
	var res Publication
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
